### ISSUE TITLE
SET-UP KANBAN BOARD

### ISSUE THREAD

**Issue by peterboro** [peterboro/Recipe-App#13]
# Dear Reviewer(s)

- Here is a link to our [KANBAN BOARD](https://github.com/users/peterboro/projects/1).
- We are a group of Two @chimwemwe007 and @peterboro

**Comment by Davidosky007** [comment]
Hi @peterboro @chimwemwe007 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All information provided in issue comment 👍 
* Link to Kanban board working perfectly 👍   
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by peterboro** [comment]
Thank you.

**Comment by peterboro** [comment]
Thank you.
